name: dcm_mobile
description: DCM Mobile - Tezgah Kontrol Uygulaması (Clean Architecture + BLoC)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.6.0
  get_it: ^7.6.7
  go_router: ^14.1.4
  json_annotation: ^4.9.0
  easy_localization: ^3.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1E1E1E"
  image: assets/logo.png
  image_dark: assets/logo.png
  fullscreen: false
  android_12:
    color: "#ffffff"
    color_dark: "#1E1E1E"
    image: assets/logo.png
    image_dark: assets/logo.png
  web: false

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21
